version: '2'
template:
  name: "Vehicle Manufacture Sample"
  description: "Deploy the IBM Blockchain Vehicle Manufacture Sample to IBM Cloud."
  required:
    - repo
    - build

toolchain:
  name: 'vehicle-manufacture-sample-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: 'https://github.com/ibm-blockchain/vehicle-manufacture'
      type: clone
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      sin: 'test'
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          SPACE_NAME: '{{form.pipeline.parameters.deploy-space}}'
          ORG_NAME: '{{form.pipeline.parameters.deploy-organization}}'
          REGION_ID: '{{form.pipeline.parameters.deploy-region}}'
          BLOCKCHAIN_SERVICE_INSTANCE: '{{form.pipeline.parameters.blockchain-service-instance}}'
          CLOUDANT_SERVICE_INSTANCE: '{{form.pipeline.parameters.cloudant-service-instance}}'
        execute: true

form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      deploy-region: '{{region}}'
      deploy-organization: '{{organization}}'
      deploy-space: '{{space}}'
      blockchain-service-instance: '{{sin}}'
      cloudant-service-instance: 'vehicle-manufacture-cloudant-service'
